### ISSUE TITLE
No such file or directory: /../../common/printer.py

### ISSUE THREAD

**Issue by shanepeckham** [bepuca/azureml-scaffolding#12] opened 2022-10-19 14:37 UTC
Steps:

1) Clone repo with git clone -c core.symlinks=true https://github.com/bepuca/azureml-scaffolding.git
2) Modify conf.env
3) Install the requirements.txt in the conda env
4) Run pre-commit in the conda env
5) Make new-exp exp=arc
6) Delete the example_experiment
7) Delete src/common
8) Modify experiment_name property in the azure-ml-job.yaml to arc
9) Modify compute name in azure-ml-job.yaml
10) Set inputs.data_path.path to existing Workspace Dataset
11) Run make job exp=arc

Met error <class 'FileNotFoundError'>:[Errno 2] No such file or directory: '/Users/shanepeckham/sources/azureml-scaffolding/../../common/printer.py'
Please check log by running the command with '--debug' for more details.

![image](https://user-images.githubusercontent.com/9840775/196721816-d65d37e1-85d1-4877-bb14-523d6b2415b5.png)

**Comment by bepuca** [comment] 2022-10-20 07:42
Hey @shanepeckham , thank you for your feedback!

The problem will be resolved if you delete the `common` folder inside your `arc` experiment. The symlink there points to a file that is originally in `./src/common`. Since you deleted it (as the docs suggest), it cannot find it anymore.

I will update the docs to make this more clear and close this issue after.

**Comment by bepuca** [comment] 2022-10-26 14:15
The clarification has been added to the README. Hence, I close the issue.

**Closed by bepuca** 2022-10-26 14:15 UTC

**Comment by seddamani** [comment] 2023-08-25 09:32
Hi @bepuca!

Thanks for your answer, I seem to be facing a similar issue and believe it goes deeper.

I performed the same steps as @shanepeckham except:
  7. I did not delete `src/common` 
  8. I ensured I added the dependency in my new experiment and it executed well with `make local exp=my_exp`

However, I am facing the same `FileNotFoundError` when running `make job exp=my_exp`.

When looking at the path in the error above, it says:
- Met error <class 'FileNotFoundError'>:[Errno 2] No such file or directory: '/Users/shanepeckham/sources/azureml-scaffolding/../../common/printer.py'
I believe if the issue was because of deleting `./src/common`, it would have said something like:
- Met error <class 'FileNotFoundError'>:[Errno 2] No such file or directory: '/Users/shanepeckham/sources/azureml-scaffolding/**_src/common_**/printer.py'

I think the problem is actually closer to this issue https://github.com/Azure/azure-sdk-for-python/issues/27980. Were you aware of this issue @bepuca? Do you have an idea for a workaround?

Thanks for your help!
